print("die_Initialize")
print("Context", context)
print("Blackboard", context:getBlackboard())
--context:getBlackboard():set("Name", "Chen Peng")
context:getBlackboard():addLuaSource("Name", function() return {1, "Chen Peng"} end, 10000)
